
public enum Accessibility {
	SERVICE_ANIMAL,
	HEARING_ACCESSABILITY_KIT,
	VISUAL_ACCESSABILITY_KIT,
	VISUAL_FIRE_SMOKE_DETECTOR,
	GRAB_BARS_IN_BATHROOM,
	LEVER_LOCK_SYSTEM,
	ALTERNATIVE_TEXT_PLACARD,
	SHOWER_SEATS,
}
